version: '3'

services:
  nginx:
    build: ./nginx
    #image: nginx:latest
    ports:
      - 1337:80
    volumes:
      - ./:/app
      - ./nginx:/etc/nginx.conf.d
    depends_on:
      - web
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data:/var/lib/postgresql/data
      - "./init/:/docker-entrypoint-initdb.d/"
    environment:
      - POSTGRES_DB=moockt
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=321
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=moockt
      - DJANGO_DB_USERNAME=root
      - DJANGO_DB_PASSWORD=321
    ports:
      - "8000:8000"
    command: gunicorn Moocacha_KakaoTalk.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - ./:/app/
    expose:
      - "8000"
