# Generated by Django 3.0.8 on 2020-07-28 03:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moocacha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='op',
            field=models.CharField(default=datetime.datetime(2020, 7, 28, 3, 41, 38, 572551, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='shifted',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
