# Generated by Django 3.0.8 on 2020-08-04 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moocacha', '0002_auto_20200728_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='session_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
